"""add parent chunks

Revision ID: ad2e1df4ce24
Revises: f500b282fd47
Create Date: 2026-07-25 12:44:10.047672

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad2e1df4ce24'
down_revision: Union[str, Sequence[str], None] = 'f500b282fd47'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chunks', sa.Column('parent_text', sa.Text(), nullable=True))
    op.add_column(
        "chunks",
        sa.Column(
            "chunk_type",
            sa.String(),
            nullable=False,
            server_default="child",
        ),
    )
    op.add_column('chunks', sa.Column('parent_chunk_id', sa.Integer(), nullable=True))
    op.create_foreign_key(
        'chunks_parent_chunk_id_fkey',
        'chunks',
        'chunks',
        ['parent_chunk_id'],
        ['id'],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('chunks_parent_chunk_id_fkey', 'chunks', type_='foreignkey')
    op.drop_column('chunks', 'parent_chunk_id')
    op.drop_column('chunks', 'chunk_type')
    op.drop_column('chunks', 'parent_text')
    # ### end Alembic commands ###
