"""create invitations table

Revision ID: f500b282fd47
Revises: 6ed7a7c9c417
Create Date: 2026-07-13 17:49:27.385991

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f500b282fd47'
down_revision: Union[str, Sequence[str], None] = '6ed7a7c9c417'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Legacy rows predate per-business grants and cannot be converted safely.
    # Add the column as nullable, revoke/scrub those bearer grants, then remove
    # them before enforcing the model's required business relationship.
    op.add_column('invitations', sa.Column('business_id', sa.Integer(), nullable=True))
    op.add_column('invitations', sa.Column('token', sa.String(), nullable=True))
    op.add_column('invitations', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.execute("UPDATE invitations SET status = 'revoked'")
    op.execute("DELETE FROM invitations")
    op.alter_column(
        'invitations',
        'business_id',
        existing_type=sa.Integer(),
        nullable=False,
    )
    op.alter_column('invitations', 'org_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('invitations', 'role',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('invitations', 'status',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_index(op.f('ix_invitations_business_id'), 'invitations', ['business_id'], unique=False)
    op.create_index(op.f('ix_invitations_id'), 'invitations', ['id'], unique=False)
    op.create_index(op.f('ix_invitations_org_id'), 'invitations', ['org_id'], unique=False)
    op.create_foreign_key(
        'invitations_business_id_fkey',
        'invitations',
        'businesses',
        ['business_id'],
        ['id'],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('invitations_business_id_fkey', 'invitations', type_='foreignkey')
    op.drop_index(op.f('ix_invitations_org_id'), table_name='invitations')
    op.drop_index(op.f('ix_invitations_id'), table_name='invitations')
    op.drop_index(op.f('ix_invitations_business_id'), table_name='invitations')
    op.alter_column('invitations', 'status',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('invitations', 'role',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('invitations', 'org_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('invitations', 'created_at')
    op.drop_column('invitations', 'token')
    op.drop_column('invitations', 'business_id')
    # ### end Alembic commands ###
